version: '3.8'

services:
  frontend:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:3001

  backend:
    build:
      context: ./backend
    ports:
      - '3001:3001'
    environment:
      - DATABASE_URL=postgres://username:password@db:5432/teste
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: teste
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
